version: '3.7'
services:
  postgres:
    image: postgres:14.5
    container_name: u2c-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker/database/postgres/initdb/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=u4c,u4c_test
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    tmpfs:
      - /var/lib/postgresql
volumes:
  postgres:
    driver: local
